---
language: python
services: docker
python: "2.7"

env:
  - distribution: ubuntu
    version: 1804
  - distribution: debian
    version: 8
  - distribution: debian
    version: 9

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local
